### PR TITLE
ER Diagram and Schema

### PR DESCRIPTION
**Pull request by praduman03**
This PR includes the following changes:
1. Created and added an ER Diagram for the Database.
2. Created and added Schema Diagram for the Database

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Add the loom video explaining the Diagrams. Explain each and every entities with all connections in detail.

**Comment by praduman03** [comment]
ERD_Diagram

**Comment by praduman03** [comment]
Schema

**Comment by praduman03** [comment]
I have done an explanation of this PR [here](https://www.loom.com/share/748b27e14e3444d5a9d7a306e0166437?sid=fa7df0df-53c0-41ee-8ea7-d093bbfdb85d).

**Comment by Kalvium-Program** [comment]
we couldn't access the loom link, give public access

**Comment by PRASANNAPATHI** [comment]
We couldn't able to access your loom video, give public access to that link.

**Comment by PRASANNAPATHI** [comment]
Diagrams and Explanations are fine,

you can merge it now

**Pull request merged**
