### PR TITLE
 DML and DDL command

### PR DESCRIPTION
**Pull request by praduman03**
This PR has the following changes:
1. DML
2. DDL

### CODE REVIEW

**Comment by praduman03** [comment]
I have done an explanation of this PR [here](https://www.loom.com/share/e19e9ef5efbd40e589161b550c534914?sid=f9c11ff5-8997-4f46-a6a0-5dfa2e5ffd3f) .

**Comment by PRASANNAPATHI** [comment]
Hey @praduman03, I don't know whether you are aware of what to submit.

you explained only commands common functionality, but where is your full sql file & explanation of your project work?

you need to create all the tables of your project and then execute & show each and every DDL commands with full proper explanation of keys and contraints of every attibutes.

Same as, for DML, you need to write the all DML commands on your tables, and execute each working with explanation.

Please, resubmit the video with all the necessary things mentioned above.

**Comment by praduman03** [comment]
Hey @PRASANNAPATHI ,I've submitted the folder containing the SQL files where the concept has been outlined, as the project is in progress, how can I create all the tables now as the project is in progress? I have created two tables as of now.

**Comment by PRASANNAPATHI** [comment]
Creating tables is not a big matter praduman, also you had time since 25th september.

These DDL & DML submission needs all the things that we mentioned in the above comment.

Please do all the necessary things, and resubmit.

**Comment by praduman03** [comment]
Hey @PRASANNAPATHI, but it is not mentioned anywhere to create all the table for this concepts ?

**Comment by praduman03** [comment]
Added more tables and made an explanation [here](https://www.loom.com/share/5193dcadc559410fb06f1b4c84f2151a?sid=eadc36a5-1ff3-4eff-a257-b6cbf15c2aa9).

**Comment by PRASANNAPATHI** [comment]
Hey @praduman03 ,
1. Customer table is missing.
2. And you have done only Create command. Alter & Drop commands are missing.
3. And the main thing missed is execution of commands, and the explanation related to that.

Please book a slot in my calendar for a viva session, you can find the link in the wiki.

**Comment by praduman03** [comment]
EXplained working of DML command [here](https://www.loom.com/share/2cfd7f85bc3d4a8c9139b1efb522afa1)
Explanation of working of DDL command [here](https://www.loom.com/share/8640067e3c8a4efca97461329ec557a3?sid=50d65431-d680-45db-bb9d-5868af7a70db), Part 2- [link](https://www.loom.com/share/a30646671aaf4f0287144ed79f5abb92)

**Comment by PRASANNAPATHI** [comment]
No @praduman03 , this is not sufficient, and not fully meeting with the comments given.

Please book a slot for viva.

**Comment by praduman03** [comment]
> No @praduman03 , this is not sufficient, and not fully meeting with the comments given.
> 
> Please book a slot for viva.

Please join the meet @PRASANNAPATHI

**Comment by PRASANNAPATHI** [comment]
Please update the sql, as discussed in meet.

**Comment by PRASANNAPATHI** [comment]
Yes @praduman03 , Its fine now, 

Please merge it for DDL.

**Comment by PRASANNAPATHI** [comment]
For DML, Please make another video, with all the necessary things, as informed in meet.

**Comment by praduman03** [comment]
Made a new video for DML commands,
[PART 1](https://www.loom.com/share/e8ab90d3edd54360b10211be0a3d5833?sid=17938561-0687-492b-b615-5f56daa9091f)
[PART 2](https://www.loom.com/share/c98e522651a447018d0b73943c0fd083?sid=733d913b-fcca-4d66-bf69-ce6ba31a7895)

**Comment by PRASANNAPATHI** [comment]
Hi @praduman03 , 

Everything is fine, but the only thing to point out is, 'false' or '0' data type - you are not sure on that. In update command you set the status to '0' which is already in '0', so no change.  Please try to have proper preparation before taking video.

Please merge it now for DML.

**Comment by praduman03** [comment]
@PRASANNAPATHI , Actually in the video I accidentaly ran the script which changed it to 0 and then I showed the table that's why, should I change it now?

**Comment by PRASANNAPATHI** [comment]
@praduman03 If you want update in your score, you can make another video only for that attribute 'status' data type clarification (with desc table) and that update command with proper logic.

**Comment by praduman03** [comment]
Here's the explanation: [Link](https://www.loom.com/share/0cff62f3c7c841c694da958c979dd2bb?sid=7a376d95-7b36-4584-923c-0160f12f1e2b)
Forgot to add the desc of table, here's the [video](https://www.loom.com/share/af67e7c3cd9e487ea20a883a463a0b2f?sid=6ff36fdc-1f1a-496d-b0a5-b10b46b3b05c)

**Comment by praduman03** [comment]
Here's the explanation: [Link](https://www.loom.com/share/0cff62f3c7c841c694da958c979dd2bb?sid=7a376d95-7b36-4584-923c-0160f12f1e2b)
Forgot to add the desc of table, here's the [video](https://www.loom.com/share/af67e7c3cd9e487ea20a883a463a0b2f?sid=6ff36fdc-1f1a-496d-b0a5-b10b46b3b05c)

**Comment by PRASANNAPATHI** [comment]
Yes @praduman03 , Everything is fine now.

Please merge it for DML.

**Pull request merged**
