### PR TITLE
Role Based Access And Advance SQL Quesries

### PR DESCRIPTION
**Pull request by praduman03**
I have added the following concepts to this PR: 
1. Role Based Access Control
2. Advance SQL Queries (where, group by, having)

### CODE REVIEW

**Comment by praduman03** [comment]
I've done an explanation of this PR [here](https://www.loom.com/share/7745b9cf3af74f7e89b5e220174ba712?sid=dd811172-43ae-4f78-b703-56ff72436b81).
[PART2](https://www.loom.com/share/b9caf1a2e8e6454b8bbfcaf5cf9dd263?sid=263757b4-3c74-46e7-830e-8e37f69cd7fd)

**Comment by PRASANNAPATHI** [comment]
Hey @praduman03 ,

For Advanced SQL Queries, your explanation and queries are good, but subquery concept is missing.

Please, you can merge it now for Advanced Sql queries.

If you need to score fully, then please submit one more query where you apply subquery concept.

**Comment by PRASANNAPATHI** [comment]
For RBAC, your explanation and commands are fine,

Please merge it now for RBAC.

Both concepts are approved to merge.

**Comment by praduman03** [comment]
[Here's ](https://www.loom.com/share/a74f9e9caa194622a5be9c61e0fc1862?sid=f69842d2-cb9f-462d-bbd2-bca7c7c00e5a) the video explaining subquery concept

**Comment by PRASANNAPATHI** [comment]
Yes @praduman03 , Good to go,

Please merge it now.

**Pull request merged**
