### PR TITLE
Transaction & Indexing

### PR DESCRIPTION
**Pull request by praduman03**
This PR includes the following changes:
1. Transaction Control Language commands
2. Indexing and query optimization

### CODE REVIEW

**Comment by praduman03** [comment]
I have done an explanation of the concepts below:
[PART 1](https://www.loom.com/share/c9b0f7be52054158849110e6fb279bdd?sid=e2ba2dbd-3025-4b19-a826-8ca1597f1c49)
[PART 2](https://www.loom.com/share/544f719785ee43d397f9d87105a29aab?sid=dfb89a67-f435-4823-bd7e-4a4297376fae)

**Comment by PRASANNAPATHI** [comment]
Hi @praduman03 ,

Your explanation and queries are good and sufficient for both the concepts.

But for Indexing & Query Optimization, you need to show the execution time before & after indexing (show the effect of indexing).

However, both TCL and Indexing & Query Optimization are approved to merge.

If you need to score fully in indexing concept, then please resubmit it with the required things mentioned above.

**Comment by praduman03** [comment]
[here's](https://www.loom.com/share/a2e078854e84497e81f9476215276897?sid=99bd4159-e5db-4ee6-9731-3bca9eef92cc) the video with the execution times for indexing

**Comment by PRASANNAPATHI** [comment]
Its Fine,
Please merge it now.

**Pull request merged**
