### PR TITLE
Normalization

### PR DESCRIPTION
**Pull request by praduman03**
This PR includes the following concepts:
1. Relational Data Model and Normalization

I've explained the concept [here](https://www.loom.com/share/6ed226a11f2c48ddb3286db6d9f30895?sid=d26b8eac-fa1f-4e14-a10c-a5055316af57).
[PART-2](https://www.loom.com/share/867b51ca5b834c3ea7caed8023d27ef9?sid=5d66098d-b70b-4bd3-bfc2-d133f28fa41f)

### CODE REVIEW

**Comment by PRASANNAPATHI** [comment]
Hi @praduman03 , concepts explanation are fine.

But implementation in your project - you just showed 1st normal form, and simply said every table follows 1st & 2nd normal form,
You need to explain how 2nd, 3rd,... normal forms (wherever applicable) are done in your tables.

You can merge it now.

If you want to score fully, then please make another video with the above mentioned things.

**Comment by praduman03** [comment]
[here's](https://www.loom.com/share/bb3c3318c2a242ba9e796e8745db2717?sid=c5b16764-335f-47e6-b8b5-936f4945e5f0) the updated video

**Comment by PRASANNAPATHI** [comment]
Hey @praduman03 , I can see mistakes in your understanding of normal forms while explaining with tables.
Please book a viva slot using the link shared in the wiki.

**Comment by PRASANNAPATHI** [comment]
Approved in Viva,

Please merge it now.

**Pull request merged**
