### PR TITLE
interface and templates

### PR DESCRIPTION
**Pull request by praduman03**
This PR includes the following concepts:
1. Interface
2.  Templates

### CODE REVIEW

**Comment by praduman03** [comment]
I have done an explanation of the concepts [here](https://www.loom.com/share/04755adec3f04b4c8f2e09572667390a?sid=8acfa2fd-bfc9-466d-9f2a-0db7276eb2be).

**Review by th3c0d3br34ker — CHANGES_REQUESTED** [review]
thanks @praduman03 for your submission - 

1. the self-viva is satisfactory for `Interface`. 
2. for `Template` just explanation is not enough. a demonstration of the concept is required. either demonstrate it in your code, or use a concept which can be demonstrated with the programming language of your choice.

thanks

**Comment by praduman03** [comment]
I have demonstrate the template concept in this [video](https://www.loom.com/share/18050d971fe24e8aba72dbc99c02f831?sid=9a44384f-3c9d-491d-9fb5-d425b58bd9f3).

**Comment by th3c0d3br34ker** [comment]
thanks @praduman03 for reverting. please go ahead and merge this PR.

**Review by th3c0d3br34ker — APPROVED** [review]

**Pull request merged**
